### PR TITLE
fix: Use appropriate timeouts

### LINKED ISSUE #685: Refactor client timeouts - parity with Python implemenation
Due to some API calls having too long default timeout, the crawlers can "freeze" for several minutes waiting for api call. In Python version this was fixed by reducing the default timeout for some endpoints and increasing the timeout in case of retries.

See Python implementation for context: https://github.com/apify/apify-client-python/pull/384
Original issue: https://github.com/apify/crawlee-python/issues/1132

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #685
- modelled after https://github.com/apify/apify-client-python/pull/384

### CODE REVIEW

File: src/http_client.ts [hunk 1]
```diff
@@ -152,13 +152,21 @@ export class HttpClient {
...
                     // Handling redirects is not possible without buffering - part of the stream has already been sent and can't be recovered
                     // when server sends the redirect. Therefore we need to override this in Axios config to prevent it from buffering the body.
                     // see also axios/axios#1045
                     config = { ...config, maxRedirects: 0 };
                 }
+
+                // Increase timeout with each attempt. Max timeout is bounded by the client timeout.
+                config.timeout = Math.min(
+                    this.timeoutMillis,
+                    config.timeout ?? this.timeoutMillis * 2 ** (attempt - 1),
```
Comment (barjin) [inline src/http_client.ts:167]: Nullish coalescing has lower precedence than multiplication. 

This would evaluate to `config.timeout ?? (this.timeoutMillis * 2 ** (attempt - 1))` (see the parentheses), which - in case `config.timeout` is `undefined` - would cause the `.min` operator to always resolve to `this.timeoutMillis` (the first expression).

Did you want to use `(config.timeout ?? this.timeoutMillis) * 2 ** (attempt - 1)`? (see parentheses)

File: src/resource_clients/request_queue.ts [hunk 2]
```diff
@@ -39,14 +42,17 @@ export class RequestQueueClient extends ResourceClient {
         });
 
         this.clientKey = userOptions.clientKey;
-        this.timeoutMillis = userOptions.timeoutSecs ? userOptions.timeoutSecs * 1e3 : undefined;
+        this.timeoutMillis = userOptions.timeoutSecs;
```
Comment (barjin) [inline src/resource_clients/request_queue.ts:45]: This looks confusing (millis / secs). Perhaps you want to rename the class field? (I see below you're using it as seconds).

File: src/resource_clients/request_queue.ts [hunk 3]
```diff
@@ -79,7 +88,9 @@ export class RequestQueueClient extends ResourceClient {
         const response = await this.httpClient.call({
             url: this._url('head'),
             method: 'GET',
-            timeout: this.timeoutMillis,
+            timeout: this.timeoutMillis
+                ? Math.min(SMALL_TIMEOUT_SECS * 1000, this.timeoutMillis)
```
Comment (barjin) [inline src/resource_clients/request_queue.ts:92]: yeah, it's confusing, millis are now seconds, so you'd need to multiply this too :sweat_smile:

Please revisit this :pray:

**Review by barjin — CHANGES_REQUESTED** [review]
+1 for extracting the consts somewhere, so we don't have those in multiple places

File: src/resource_clients/dataset.ts [hunk 4]
```diff
@@ -9,6 +9,10 @@ import type { ApifyRequestConfig, ApifyResponse } from '../http_client';
 import type { PaginatedList } from '../utils';
 import { cast, catchNotFoundOrThrow, pluckData } from '../utils';
 
+const SMALL_TIMEOUT_SECS = 5; // For fast and common actions. Suitable for idempotent actions.
+const MEDIUM_TIMEOUT_SECS = 30; // For actions that may take longer.
+const DEFAULT_TIMEOUT_SECS = 360; // 6 minutes
```
[the remark this answers is not in the document]
Comment (janbuchar) [reply src/resource_clients/dataset.ts:14]: the python version also repeats those, but yeah, let's do that

**Comment by janbuchar** [comment]
Sorry for the confusion around secs/millis - I changed my approach when working on this and stopped when the client_timeouts test started to pass :facepalm:

**Review by barjin — APPROVED** [review]

File: src/base/resource_client.ts [hunk 5]
```diff
@@ -13,16 +13,21 @@ import { ApiClient } from './api_client';
...
+export const MEDIUM_TIMEOUT_SECS = 30; // For actions that may take longer.
+export const DEFAULT_TIMEOUT_SECS = 360; // 6 minutes
+
 /**
  * Resource client.
  * @private
  */
 export class ResourceClient extends ApiClient {
-    protected async _get<T, R>(options: T = {} as T): Promise<R | undefined> {
+    protected async _get<T, R>(options: T = {} as T, timeoutSecs?: number): Promise<R | undefined> {
```
[the remark this answers is not in the document]
Comment (janbuchar) [reply src/base/resource_client.ts:25]: `ApifyClient` and `HttpClient` already accept `timeoutSecs`, so I'm afraid that ship has sailed... But you have a good point that these methods are only used internally, so it would make the internals of the resource clients a bit more uniform.

**Comment by janbuchar** [comment]
@B4nan @barjin I switched to milliseconds almost everywhere and I think the result is in fact much cleaner. If you want to skim it, go ahead. Otherwise I'll merge it later today.
